version: '3.8'

services:
  php:
    container_name: laravel_app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    volumes:
      - ./../code:/var/www/html
#      - /var/www/html/vendor
    depends_on:
      - mysql_db
    command: sh -c "php artisan migrate:fresh || echo 'Migration failed'; php artisan db:seed || echo 'Seeding failed'; apache2-foreground"

  mysql_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}
    volumes:
      - ./../Database/mysql-data:/var/lib/mysql

volumes:
  mysql-data: